FedFor01/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Threading.Tasks;
using System;
using FedFor01.Models;
using System.Collections.Generic;
using System.Text;


namespace FedFor01.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();

        }


        [HttpGet]
        public ActionResult Facility()
        {

            List<RECDATA> Lcamp = new List<RECDATA>();
            ViewBag.count = 0;
            ViewBag.lat = 0;
            ViewBag.lng = 0;

            return View(Lcamp);


            //           var t = Task.Run(() => AwaitOperatorCustom.curlRequestAsync(usersearch: null, offset: 0, usercount: 0, state: null, sort: null, activity: null));
            //t.Wait();
            //return View(t.Result);
        }

        [HttpPost]
        public ActionResult Facility(string lat, string lng, string search, string searchnumber, string stateinitial, string sort, string[] activity, string offset)
        {
            ViewBag.Message = "find a site.";

            ViewBag.offsetnumber = offset;

            switch (sort)
            {
                case "Name":
                    ViewBag.NameSelect = "selected";
                    break;

                case "ID":
                    ViewBag.IDSelect = "selected";
                    break;

                case "Date":
                    ViewBag.DateSelect = "selected";
                    break;
            }

            string activitystring = "";
            if (activity?.Length > 0)
            {
                StringBuilder builder = new StringBuilder();
                int i = 1;
                foreach (string value in activity)
                {
                    if (i == activity.Length) //Use count or length as supported by your collection
                    {
                        builder.Append(value);
                    }
                    else
                    {
                        builder.Append(value);
                        builder.Append(',');
                        i++;
                    }
                }
                activitystring = builder.ToString();

            }

            int searchnumberint = 50;
            if (string.IsNullOrEmpty(searchnumber) == false)
            {
                searchnumberint = Int32.Parse(searchnumber);
            }

            int offsetVal = 0;
            if (string.IsNullOrEmpty(offset) == false)
            {
                offsetVal = Int32.Parse(offset);
            }

            ViewBag.lat = lat;
            ViewBag.lng = lng;

            var t = Task.Run(() => AwaitOperatorCustom.curlReloadAsync(usersearch: search, offset: offsetVal, usercount: searchnumberint, state: stateinitial, sort: sort, activity: activitystring, lat: lat, lng: lng));
            t.Wait();
            ViewBag.count = t.Result.Count.ToString();
            return View(t.Result);
        }


        public ActionResult FacilitySearch(string search, string searchnumber, string stateinitial, string sort, string activity, string offset)
        {
            int searchnumberint = 50;
            if (string.IsNullOrEmpty(searchnumber) == false)
            {
                searchnumberint = Int32.Parse(searchnumber);
            }

            int offsetVal = 0;
            if (string.IsNullOrEmpty(offset) == false)
            {
                offsetVal = Int32.Parse(offset);
            }

            var t = Task.Run(() => AwaitOperatorCustom.curlRequestAsync(usersearch: search, offset: offsetVal, usercount: searchnumberint, state: stateinitial, sort: sort, activity: activity));
            t.Wait();
            return View(t.Result);
        }

        [HttpGet]
        public ActionResult FacilityMapSearch()
        {
            var t = Task.Run(() => AwaitOperatorCustom.curlRequestAsync(usersearch: null, offset: 0, usercount: 0, state: null, sort: null, activity: null));
            t.Wait();
            return View(t.Result);


            //int offset = 0;
            //void IncreaseOffset()
            //{
            //    offset = offset + 50;
            //}
        }

        [HttpPost]
        public ActionResult FacilityMapSearch(string search, string searchnumber, string stateinitial, string sort, string[] activity, string offset)
        {

            ViewBag.offsetnumber = offset;
            ViewBag.searchnumber = 10;

            switch (sort)
            {
                case "Name":
                    ViewBag.NameSelect = "selected";
                    break;

                case "ID":
                    ViewBag.IDSelect = "selected";
                    break;

                case "Date":
                    ViewBag.DateSelect = "selected";
                    break;
            }

            switch (searchnumber)
            {
                case "10":
                    ViewBag.searchnumber10 = "selected";
                    break;

                case "25":
                    ViewBag.searchnumber25 = "selected";
                    break;

                case "50":
                    ViewBag.searchnumber50 = "selected";
                    break;
            }

            string activitystring = "";
            if (activity?.Length > 0)
            {
                StringBuilder builder = new StringBuilder();
                int i = 1;
                foreach (string value in activity)
                {
                    if (i == activity.Length) //Use count or length as supported by your collection
                    {
                        builder.Append(value);
                    }
                    else
                    {
                        builder.Append(value);
                        builder.Append(',');
                        i++; 
                    }
                }
                activitystring = builder.ToString();

            }

            int searchnumberint = 10;
            if (string.IsNullOrEmpty(searchnumber) == false)
            {
                searchnumberint = Int32.Parse(searchnumber);
                ViewBag.searchnumber = searchnumber;

            }

            int offsetVal = 0;
            if (string.IsNullOrEmpty(offset) == false)
            {
                offsetVal = Int32.Parse(offset);
            }

            var t = Task.Run(() => AwaitOperatorCustom.curlRequestAsync(usersearch: search, offset: offsetVal, usercount: searchnumberint, state: stateinitial, sort: sort, activity: activitystring));
            t.Wait();
            return View(t.Result);

            //int offset = 0;
            //void IncreaseOffset()
            //{
            //    offset = offset + 50;
            //}
        }

    }
}

FedFor01/Controllers/RECDATAsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
//using FedFor01.Data;
using FedFor01.Models;
using System.Threading.Tasks;
using System.Text;

namespace FedFor01.Controllers
{
    public class RECDATAsController : Controller
    {
        //private FedFor01Context db = new FedFor01Context();

        // GET: RECDATAs
        public ActionResult Index()
        {
            var t = Task.Run(() => AwaitOperatorCustom.curlRequestAsync(usersearch: null, offset: 0, usercount: 50, state: null, sort: null, activity: null));
            t.Wait();
            return View(t.Result);
        }

        // GET: RECDATAs/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return HttpNotFound();
            }

            var t = Task.Run(() => AwaitOperatorFacility.curlRequestAsyncTest(facilityID: id));
            t.Wait();
            //var model = t.Result;
            //ViewBag.test = model;
            return View(t.Result);
        }


    }
}

FedFor01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FedFor01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FedFor01/Views/Home/Details.cshtml
@model FedFor01.Models.RECDATA

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>RECDATA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FacilityID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LegacyFacilityID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegacyFacilityID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgFacilityID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgFacilityID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentOrgID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentOrgID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentRecAreaID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentRecAreaID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityUseFeeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityUseFeeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityDirections)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityDirections)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityReservationURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityReservationURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityMapURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityMapURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityAdaAccess)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityAdaAccess)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityLongitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityLongitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityLatitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityLatitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StayLimit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StayLimit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Keywords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Keywords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reservable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reservable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Enabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Enabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FedFor01/Views/Home/Facility.cshtml
@model List<FedFor01.Models.RECDATA>
<head>

    <title>Facility</title>
    <style>
        /* Set the size of the div element that contains the map */
        #map {
            height: 400px; /* The height is 400 pixels */
            width: 100%; /* The width is the width of the web page */
        }
    </style>
</head>

@* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IGNORE THIS PAGE, ONLY KEPT FOR ARCHIVAL PURPOSES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! *@



<body>
    <div id="map"></div>
    <script type="text/javascript">

        document.getElementById("myform").addEventListener('submit', function (event) {
            event.preventDefault()
        });


        function SendData() {
            alert("here1");
            var myform = document.getElementById("myform");
            var fd = new FormData(myform)
            alert(fd.get("stateinitial"));


        }



        function formtodata() {
            alert("here1");
            return false;

        }

        //var myform = document.getElementById(myform);

        function targetFac(plat, plog) {

            alert("here1");
            var myform = document.getElementById("myform");
            var fd = new FormData(myform)
            alert(fd.get("activity"));

             $.ajax({
                 url: 'Facility',
                 data: {
                     lat: plat, lng: plog, stateinitial: fd.get("stateinitial"), sort: fd.get("sort"), offset: fd.get("offset"), search: fd.get("search"), searchnumber: fd.get("searchnumber"), activity: fd.get("activity") },
               type: "POST",
               success: function (data) {
                 $("body").html(data,map);
               }
           });
        }

       function initMap() {

           var myLat= @ViewBag.lat;
           var mylng = @ViewBag.lng;
           var count = @ViewBag.count;

           if (count == 0) {
               //// Create the map.

               var map = new google.maps.Map(document.getElementById("map"), {
                   zoom: 7,
                   center: { lat: 37.6876, lng: -91.0828 },
                   mapTypeId: google.maps.MapTypeId.ROADMAP
               });
           } else {

               var map = new google.maps.Map(document.getElementById("map"), {
                   zoom: 10,
                   center: { lat: myLat, lng: mylng },
                   mapTypeId: "terrain"
               });

              @foreach (var item in Model) {
                   @:addMarker(@item.FacilityLatitude, @item.FacilityLongitude, '@item.FacilityName', '@Uri.EscapeUriString(item.FacilityDescription)', map);
                          }
           }

           map.addListener('click', function (mapsMouseEvent) {
               targetFac(mapsMouseEvent.latLng.lat(), mapsMouseEvent.latLng.lng() );

           });

    }

    // Declare addMarker function
       function addMarker(latitude, longitude, title, Description,  map)
    {
           var latLng = new google.maps.LatLng(latitude, longitude);
           var contentString = '<h3>' + title + '</h3>' + '<p> ' + decodeURI(Description); + '</p>';

           var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position: latLng,
            title: title,
            Description: decodeURI(Description),
            map: map,
            draggable: false
        });

        google.maps.event.addListener(marker, 'click', function () {
             infowindow.open(map, marker);
        });



    }


    </script>

    @*<script>
            formtodata
        </script>*@

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCsRgeXCc_jaRPraI_XZGuEWSJgWp9wmxo &callback=initMap">
    </script>

    @*<form id="myform" name="myform">
            <b> Search: </b> @Html.Editor("search")
            <p></p>
            <b> Campsites Displayed: </b>@Html.Editor("searchnumber")

            @Html.DropDownList("stateinitial", FedFor01.Controllers.FiftyStates.StateListItems(), new { @class = "form-control" })

            <p></p>
            <b> Activity: </b> <input type="button" id="popupbutton" onclick="popup(this)" value="Activites" />
            @Html.DropDownList("activity", FedFor01.Controllers.Activities.ActivityListItems(), new { @class = "form-control", @multiple = "multiple", @size = "32", @display = "block" })


            <p></p>
            <select id='sort' name="sort">
                <option value="">Sort By</option>
                <option selected="@ViewBag.NameSelect">Name</option>
                <option selected="@ViewBag.IDSelect">ID</option>
                <option selected="@ViewBag.DateSelect">Date</option>
            </select>

            <p></p>
            <button onclick="offset.stepDown(1)">Previous 50</button>
            <input type="number" min="0" step="50" value="@ViewBag.offsetnumber" id="offset" name="offset">
            <button onclick="offset.stepUp(1)">Next 50</button>


            <p></p>
            <input type="submit" onclick="formtodata(search, searchnumber, stateinitial, sort, activity, offset)" value="Search">
        </form>*@
    @using (Html.BeginForm("Facility", "Home", FormMethod.Post, new { name = "myform", id = "myform", onsubmit = "SendData(); return false;" }))
    {
        <b> Search: </b> @Html.Editor("search")
        <p></p>
        <b> Campsites Displayed: </b>@Html.Editor("searchnumber")

        @Html.DropDownList("stateinitial", FedFor01.Controllers.FiftyStates.StateListItems(), new { @class = "form-control" });

        <p></p>
        <b> Activity: </b> <input type="button" id="popupbutton" onclick="popup(this)" value="Activites" />
        @Html.DropDownList("activity", FedFor01.Controllers.Activities.ActivityListItems(), new { @class = "form-control", @multiple = "multiple", @size = "32", @display = "block" });


        <p></p>
        <select id='sort' name="sort">
            <option value="">Sort By</option>
            <option selected="@ViewBag.NameSelect">Name</option>
            <option selected="@ViewBag.IDSelect">ID</option>
            <option selected="@ViewBag.DateSelect">Date</option>
        </select>

        <p></p>
        <button onclick="offset.stepDown(1)">Previous 50</button>
        <input type="number" min="0" step="50" value="@ViewBag.offsetnumber" id="offset" name="offset">
        <button onclick="offset.stepUp(1)">Next 50</button>

        <p></p>
        <input type="submit" @*onclick="formtodata()"*@ value="Search">
    }




    <h2>Facility</h2>
    <div id="div1">
        <table class="table">
            <thead>
                <tr class="bg-primary">
                    <th>FacilityName</th>
                    <th>FacilityID</th>
                    <th>FacilityLatitude</th>
                    <th>FacilityLongitude</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var RECDATA in Model)
                {
                    <tr>
                        <td>
                            @RECDATA.FacilityName
                        </td>
                        <td class="bg-info">
                            @RECDATA.FacilityID
                            <button id="loadFromMainFrame" onclick="targetFac(@RECDATA.FacilityLatitude,@RECDATA.FacilityLongitude)">Select</button>
                        </td>
                        <td class="bg-info">@RECDATA.FacilityLatitude</td>
                        <td class="bg-info">@RECDATA.FacilityLongitude</td>
                    </tr>
                }
            </tbody>
        </table>
        what
    </div>

</body>

FedFor01/Views/Home/FacilityMapSearch.cshtml
@model IEnumerable<FedFor01.Models.RECDATA>


@{
    ViewBag.Title = "FacilityMapSearch";
}

@{
    //int offset = 0;
}}

<script>
    var stateinitial = document.getElementById("stateinitial");
    stateinitial.options[stateinitial.options.selectedIndex].selected = true;
</script>

<head>

    <title>Facility</title>
    <style>
        /* Set the size of the div element that contains the map */
        #map {
            height: 400px; /* The height is 400 pixels */
            width: 100%; /* The width is the width of the web page */
        }
    </style>
</head>




<body>

    <div id="map"></div>
    <script type="text/javascript">

       function targetFac(plat, plog) {
           var map = new google.maps.Map(document.getElementById("map"), {
               zoom: 10,
               center: { lat: plat, lng: plog },
               mapTypeId: "terrain"
           });

         @foreach (var item in Model) {
        @:addMarker(@item.FacilityLatitude, @item.FacilityLongitude, '@item.FacilityName', '@Uri.EscapeUriString(item.FacilityDescription)',  map);
       }

       }

           function initMap()
           {

           // Create the map.
           //var map = new google.maps.Map(document.getElementById("map"), {
           //    zoom: 8,
           //    center: { lat: 37.6876, lng: -91.0828 },
           //    mapTypeId: google.maps.MapTypeId.ROADMAP
           //    });



            }

    // Declare addMarker function
       function addMarker(latitude, longitude, title, Description,  map)
            {
                   var latLng = new google.maps.LatLng(latitude, longitude);
                   var contentString = '<h3>' + title + '</h3>' + '<p> ' + decodeURI(Description); + '</p>';

                   var infowindow = new google.maps.InfoWindow({
                    content: contentString
                });

                var marker = new google.maps.Marker({
                    position: latLng,
                    title: title,
                    Description: decodeURI(Description),
                    map: map,
                    draggable: false
                });

                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.open(map, marker);
                });
            }


    </script>


    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCsRgeXCc_jaRPraI_XZGuEWSJgWp9wmxo &callback=initMap">
    </script>


    @using (Html.BeginForm("FacilityMapSearch", "Home", FormMethod.Post))
    {
        <b> Search: </b> @Html.Editor("search")
        <p></p>
        <b> Advanced Options: </b> <input type="button" id="popupbutton" onclick="popup(this)" value="Show/Hide" />
        <div id="AdvOptions" style="display: none">
            <p>State:</p>
            @Html.DropDownList("stateinitial", FedFor01.Controllers.FiftyStates.StateListItems(), new { @class = "form-control", @id = "stateinitial" })
            <p></p>
            <p></p>


            <p>Activities:</p>
            @Html.DropDownList("activity", FedFor01.Controllers.Activities.ActivityListItems(), new { @class = "form-control", @multiple = "multiple", @size = "12", @id = "activity" })


            <p></p>
            <select id='sort' name="sort" class="option">
                <option value="">Sort By</option>
                <option selected="@ViewBag.NameSelect">Name</option>
                <option selected="@ViewBag.IDSelect">ID</option>
                <option selected="@ViewBag.DateSelect">Date</option>
            </select>
            <p></p>

            <b> Display: </b> <select id='searchnumber' name="searchnumber">
                <option selected="@ViewBag.searchnumber10">10</option>
                <option selected="@ViewBag.searchnumber25">25</option>
                <option selected="@ViewBag.searchnumber50">50</option>
            </select>
            <!--<input type="button" onclick="searchnumber = 10" value="10"><input type="button" onclick="searchnumber = 25" value="25"><input type="button" onclick="searchnumber = 50" value="50">--> @*switch to "Show: 10/25/50"?*@

            <button onclick="offset.stepDown(1)">Previous @ViewBag.searchnumber</button>
            <input type="number" min="0" step="@ViewBag.searchnumber" value="0" id="offset" name="offset" />
            <button onclick="offset.stepUp(1)">Next @ViewBag.searchnumber</button>
        </div>

        <p></p>
        <input type="submit" name="submit" value="Search" class="option" />
    }

    @*<ul id="checkBundle">
            <li><label><input type="checkbox" />test1</label>
            <li><label><input type="checkbox" />test2</label>
            <li><label><input type="checkbox" />test3</label>
            <li><label><input type="checkbox" />test4</label>
        </ul>*@

    @helper UnOrderedList(IEnumerable<string> items)
    {
        <ul class="list list--two-column">
            @foreach (var item in items)
            {
                <li>
                    <div class="list-column-one">@item</div>
                    <div class="list-column-two">@item</div>
                </li>
            }
        </ul>
    }
    @*@_Page_Views_Home_FacilityMapSearch_cshtml.UnOrderedList(new[] { "One", "Two" });*@




    <script>
        function popup() {
            var popwindow = document.getElementById("AdvOptions");
            if (popwindow.style.display === "none") {
                popwindow.style.display = "block";
            } else {
                popwindow.style.display = "none";
            }
        };
    </script>


    <h2>Facility</h2>
    <div id="div1">
        <table class="table">
            <thead>
                <tr class="bg-primary">
                    <th>Facility Name</th>
                    <th>Facility ID</th>
                    <th>Facility Info</th>
                    <th>Facility Latitude</th>
                    <th>Facility Longitude</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var RECDATA in Model)
                {
                    <tr>
                        <td>
                            @RECDATA.FacilityName
                        </td>
                        <td class="bg-info">@RECDATA.FacilityID</td>
                        <td>
                            <button id="loadFromMainFrame" onclick="targetFac(@RECDATA.FacilityLatitude,@RECDATA.FacilityLongitude)">Select On Map</button>
                            @*<button id="showDetails" onclick="location.href='@Url.Action("Details", "Details", RECDATAs, new { id = RECDATA.FacilityID }, null)">Show Details</button>*@
                            @Html.ActionLink("Details", "Details", "RECDATAs", new { id = RECDATA.FacilityID }, new { @class = "btn btn-primary", @style = "color:white" })

                        </td>
                        <td class="bg-info">@RECDATA.FacilityLatitude</td>
                        <td class="bg-info">@RECDATA.FacilityLongitude</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @*  *@
</body>

@{

}

FedFor01/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>