FedFor01/Controllers/CampsiteController.cs
using System.Web.Mvc;
using System.Threading.Tasks;
using System;
using FedFor01.CampsiteModel;
using System.Collections.Generic;
using System.Text;

namespace FedFor01.Controllers
{
    public class CampsiteController : Controller
    {
        // GET: Campsite
        public ActionResult Index(string id)
        {
            var t = Task.Run(() => AwaitOperatorCampsite.curlRequestAsync(facilityID: id));
            t.Wait();
            return View(t.Result);
        }

        // GET: Campsite/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return HttpNotFound();
            }

            var t = Task.Run(() => AwaitOperatorCampsite.curlRequestAsyncSingleCamp(facilityID: id));
            t.Wait();
            //var model = t.Result;
            //ViewBag.test = model;
            return View(t.Result);
        }

        // GET: Campsite/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Campsite/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Campsite/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Campsite/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Campsite/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Campsite/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FedFor01/Controllers/RECDATAsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
//using FedFor01.Data;
using FedFor01.Models;
using System.Threading.Tasks;
using System.Text;

namespace FedFor01.Controllers
{
    public class RECDATAsController : Controller
    {
        //private FedFor01Context db = new FedFor01Context();

        // GET: RECDATAs
        public ActionResult Index()
        {
            var t = Task.Run(() => AwaitOperatorCustom.curlRequestAsync(usersearch: null, offset: 0, usercount: 50, state: null, sort: null, activity: null));
            t.Wait();
            return View(t.Result);
        }

        // GET: RECDATAs/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return HttpNotFound();
            }

            var t = Task.Run(() => AwaitOperatorFacility.curlRequestAsyncTest(facilityID: id));
            t.Wait();
            //var model = t.Result;
            //ViewBag.test = model;
            return View(t.Result);
        }


    }
}

FedFor01/Views/RECDATAs/Details.cshtml
@model FedFor01.ModelsSingle.Rootobject
@using System.Data.Entity;


@{
    ViewBag.Title = "Details";
}

@*Exists solely to activate the function when the page loads*@
<body onload="changedesc(`@Uri.EscapeUriString(Model.FacilityDescription)`, `@Uri.EscapeUriString(Model.FacilityDirections)`)">
</body>

@*Used to decode pre-formatted text into something usable*@
<script>
    function changedesc(desc, dir) {
        var DecString = decodeURI(desc);
        var DirString = decodeURI(dir);

        document.getElementById("facdesc").innerHTML = DecString
        document.getElementById("facdir").innerHTML = DirString
    }
</script>

@*Lists all properties of the selected facility*@
<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Facility ID</dt>
        <dd>@Model.FacilityID</dd>

        <dt>Legacy Facility ID</dt>
        <dd>@Model.LegacyFacilityID</dd>

        <dt>Organization Facility ID</dt>
        <dd>@Model.OrgFacilityID</dd>

        <dt>Parent Organization ID</dt>
        <dd>@Model.ParentOrgID</dd>

        <dt>Parent Rec Area ID</dt>
        <dd>@Model.ParentRecAreaID</dd>

        <dt>Facility Name</dt>
        <dd>@Model.FacilityName</dd>

        <dt>Facility Description</dt>
        <dd id="facdesc"></dd>

        <dt>Facility Type Description</dt>
        <dd>@Model.FacilityTypeDescription</dd>

        <dt>Facility Use Fee Description</dt>
        <dd>@Model.FacilityUseFeeDescription</dd>

        <dt>Facility Directions</dt>
        <dd id="facdir"></dd>

        <dt>Facility Phone</dt>
        <dd>@Model.FacilityPhone</dd>

        <dt>Facility Email</dt>
        <dd>@Model.FacilityEmail</dd>

        <dt>Facility Reservation URL</dt>
        <dd>@Model.FacilityReservationURL</dd>

        <dt>Facility Map URL</dt>
        <dd>@Model.FacilityMapURL</dd>

        <dt>Facility ADA Access</dt>
        <dd>@Model.FacilityAdaAccess</dd>

        <dt>Facility Longitude</dt>
        <dd>@Model.FacilityLongitude</dd>

        <dt>Facility Latitude</dt>
        <dd>@Model.FacilityLatitude</dd>

        <dt>Stay Limit</dt>
        <dd>@Model.StayLimit</dd>

        <dt>Keywords</dt>
        <dd>@Model.Keywords</dd>

        <dt>Reservable</dt>
        <dd>@Model.Reservable</dd>

        <dt>Enabled</dt>
        <dd>@Model.Enabled</dd>

        <dt>Last Updated Date</dt>
        <dd>@Model.LastUpdatedDate</dd>
    </dl>
</div>
<hr />
<div>
    <h4>Campsites</h4>
    @*@Html.ActionLink("Campsites", "Index", "Campsite", new { id = Model.FacilityID }, new { @class = "btn btn-primary", @style = "color:white" })*@
    <input type="button" id="popupbutton" onclick="popup(this)" value="Show list of campsites" />
    <div id="Campsites" style="display: none">@{Html.RenderAction("Index", "Campsite", new { id = Model.FacilityID });}</div>
</div>
<script>
    function popup() {
        var popwindow = document.getElementById("Campsites");
        if (popwindow.style.display === "none") {
            popwindow.style.display = "block";
        } else {
            popwindow.style.display = "none";
        }
    };
</script>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FacilityID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FedFor01/Views/RECDATAs/DetailsBase.cshtml
@model FedFor01.Models.RECDATA

@{
    ViewBag.Title = "DetailsBase";
}

<h2>Details2</h2>

<div>
    <h4>RECDATA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LegacyFacilityID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegacyFacilityID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgFacilityID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgFacilityID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentOrgID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentOrgID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentRecAreaID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentRecAreaID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityUseFeeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityUseFeeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityDirections)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityDirections)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityReservationURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityReservationURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityMapURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityMapURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityAdaAccess)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityAdaAccess)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GEOJSON)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GEOJSON)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityLongitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityLongitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacilityLatitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityLatitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StayLimit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StayLimit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Keywords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Keywords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reservable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reservable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Enabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Enabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FacilityID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FedFor01/Views/RECDATAs/Edit.cshtml
@model FedFor01.Models.RECDATA

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RECDATA</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FacilityID)

        <div class="form-group">
            @Html.LabelFor(model => model.LegacyFacilityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LegacyFacilityID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LegacyFacilityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrgFacilityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrgFacilityID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrgFacilityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentOrgID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentOrgID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParentOrgID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentRecAreaID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentRecAreaID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParentRecAreaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityTypeDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityTypeDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityTypeDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityUseFeeDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityUseFeeDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityUseFeeDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityDirections, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityDirections, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityDirections, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityReservationURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityReservationURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityReservationURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityMapURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityMapURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityMapURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityAdaAccess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityAdaAccess, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityAdaAccess, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GEOJSON, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GEOJSON, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GEOJSON, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityLongitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityLongitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityLongitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityLatitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityLatitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityLatitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StayLimit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StayLimit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StayLimit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reservable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Reservable)
                    @Html.ValidationMessageFor(model => model.Reservable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Enabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Enabled)
                    @Html.ValidationMessageFor(model => model.Enabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FedFor01/Views/RECDATAs/Index.cshtml
@model IEnumerable<FedFor01.Models.RECDATA>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FacilityID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LegacyFacilityID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrgFacilityID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParentOrgID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParentRecAreaID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityTypeDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityUseFeeDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityDirections)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityReservationURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityMapURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityAdaAccess)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityLongitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FacilityLatitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StayLimit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Keywords)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reservable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Enabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastUpdatedDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LegacyFacilityID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrgFacilityID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentOrgID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentRecAreaID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityTypeDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityUseFeeDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityDirections)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityReservationURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityMapURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityAdaAccess)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityLongitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacilityLatitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StayLimit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Keywords)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reservable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastUpdatedDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.FacilityID }) |
                @Html.ActionLink("Details", "Details", new { id = item.FacilityID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.FacilityID })
            </td>
        </tr>
    }

</table>